osx_image: xcode8
language: objective-c

xcode_sdk: iphonesimulator10.0
script:
- xcodebuild test -workspace Example/URLUtilities.xcworkspace -scheme URLUtilities-Example  ONLY_ACTIVE_ARCH=NO | xcpretty

